2025-06-11 00:58:53,998 - INFO - Starting sector portfolios generation for 2025-06-10
2025-06-11 00:59:12,421 - ERROR - Error during sector portfolios generation
Traceback (most recent call last):
  File "C:\Users\kvs39\Desktop\validityBase\Dagster\portfolio_spdrs\dagster_pipelines\assets\portfolio_asset.py", line 58, in sector_portfolios
    df_portfolios: pd.DataFrame = produce_sector_portfolios(partition_date, logger=file_logger, half_life=30)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kvs39\Desktop\validityBase\Dagster\portfolio_spdrs\dagster_pipelines\assets\portfolio_producer.py", line 163, in produce_sector_portfolios
    logger.info(f"Portfolio {etf}: beta = {beta:.4f}")
                                          ^^^^^^^^^^
TypeError: unsupported format string passed to Series.__format__
