2025-06-11 01:30:23,212 - INFO - Starting sector portfolios generation for 2025-06-01
2025-06-11 01:30:23,800 - WARNING - No trading on 2025-06-01.
2025-06-11 01:30:23,821 - ERROR - Error during sector portfolios generation
Traceback (most recent call last):
  File "C:\Users\kvs39\Desktop\validityBase\Dagster\portfolio_spdrs\dagster_pipelines\assets\portfolio_asset.py", line 58, in sector_portfolios
    df_portfolios: pd.DataFrame = produce_sector_portfolios(partition_date, logger=file_logger, half_life=30)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kvs39\Desktop\validityBase\Dagster\portfolio_spdrs\dagster_pipelines\assets\portfolio_producer.py", line 105, in produce_sector_portfolios
    raise DagsterExecutionStepExecutionError("No trading day found.")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kvs39\Desktop\validityBase\Dagster\dagster_env\Lib\site-packages\dagster\_core\errors.py", line 363, in __init__
    self.step_key = check.str_param(kwargs.pop("step_key"), "step_key")
                                    ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'step_key'
